"""Binance Spot execution persistence

Revision ID: 0007
Revises: 0006
"""
from alembic import op
import sqlalchemy as sa
revision="0007"; down_revision="0006"; branch_labels=None; depends_on=None
P=sa.Numeric(30,12); TS=sa.DateTime(timezone=True)
def timestamps(): return [sa.Column("created_at",TS,nullable=False),sa.Column("updated_at",TS,nullable=False)]
def upgrade():
    op.create_table("exchange_accounts",sa.Column("id",sa.Integer,primary_key=True),sa.Column("exchange",sa.String(32),nullable=False),sa.Column("environment",sa.String(16),nullable=False),sa.Column("account_type",sa.String(32),nullable=False),sa.Column("masked_api_key",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("permissions_json",sa.JSON,nullable=False),sa.Column("last_connected_at",TS),sa.Column("last_error",sa.String(500)),*timestamps())
    op.create_index("ix_exchange_accounts_environment","exchange_accounts",["environment"])
    op.create_table("execution_orders",sa.Column("id",sa.Integer,primary_key=True),sa.Column("exchange",sa.String(32),nullable=False),sa.Column("environment",sa.String(16),nullable=False),sa.Column("symbol_id",sa.Integer,sa.ForeignKey("symbols.id"),nullable=False),sa.Column("trade_setup_id",sa.Integer,sa.ForeignKey("trade_setups.id"),nullable=False),sa.Column("client_order_id",sa.String(64),nullable=False,unique=True),sa.Column("exchange_order_id",sa.String(64)),sa.Column("side",sa.String(8),nullable=False),sa.Column("order_type",sa.String(16),nullable=False),sa.Column("time_in_force",sa.String(8)),sa.Column("requested_quantity",P,nullable=False),sa.Column("executed_quantity",P,nullable=False),sa.Column("requested_price",P),sa.Column("average_fill_price",P),sa.Column("quote_quantity",P),sa.Column("status",sa.String(32),nullable=False),sa.Column("execution_state",sa.String(32),nullable=False),sa.Column("raw_status_json",sa.JSON,nullable=False),sa.Column("rejection_reason",sa.String(500)),sa.Column("submitted_at",TS),sa.Column("acknowledged_at",TS),sa.Column("filled_at",TS),sa.Column("canceled_at",TS),*timestamps())
    for c in ("environment","symbol_id","trade_setup_id","client_order_id","exchange_order_id","status","execution_state"): op.create_index(f"ix_execution_orders_{c}","execution_orders",[c])
    op.create_table("execution_fills",sa.Column("id",sa.Integer,primary_key=True),sa.Column("execution_order_id",sa.Integer,sa.ForeignKey("execution_orders.id",ondelete="CASCADE"),nullable=False),sa.Column("exchange_trade_id",sa.String(64),nullable=False),sa.Column("price",P,nullable=False),sa.Column("quantity",P,nullable=False),sa.Column("quote_quantity",P,nullable=False),sa.Column("commission",P,nullable=False),sa.Column("commission_asset",sa.String(16),nullable=False),sa.Column("filled_at",TS,nullable=False),sa.UniqueConstraint("execution_order_id","exchange_trade_id",name="uq_execution_fill_trade"))
    op.create_index("ix_execution_fills_execution_order_id","execution_fills",["execution_order_id"])
    op.create_table("live_positions",sa.Column("id",sa.Integer,primary_key=True),sa.Column("exchange",sa.String(32),nullable=False),sa.Column("environment",sa.String(16),nullable=False),sa.Column("symbol_id",sa.Integer,sa.ForeignKey("symbols.id"),nullable=False),sa.Column("originating_trade_setup_id",sa.Integer,sa.ForeignKey("trade_setups.id"),nullable=False),sa.Column("direction",sa.String(16),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("base_quantity",P,nullable=False),sa.Column("remaining_quantity",P,nullable=False),sa.Column("average_entry",P,nullable=False),sa.Column("stop_loss",P,nullable=False),sa.Column("take_profit_1",P),sa.Column("take_profit_2",P),sa.Column("take_profit_3",P),sa.Column("realized_pnl",P,nullable=False),sa.Column("unrealized_pnl",P,nullable=False),sa.Column("total_fees",P,nullable=False),sa.Column("opened_at",TS,nullable=False),sa.Column("closed_at",TS),*timestamps())
    for c in ("environment","symbol_id","originating_trade_setup_id","status"): op.create_index(f"ix_live_positions_{c}","live_positions",[c])
    op.create_table("execution_events",sa.Column("id",sa.Integer,primary_key=True),sa.Column("severity",sa.String(16),nullable=False),sa.Column("event_type",sa.String(64),nullable=False),sa.Column("exchange",sa.String(32),nullable=False),sa.Column("environment",sa.String(16),nullable=False),sa.Column("symbol_id",sa.Integer,sa.ForeignKey("symbols.id")),sa.Column("trade_setup_id",sa.Integer,sa.ForeignKey("trade_setups.id")),sa.Column("execution_order_id",sa.Integer,sa.ForeignKey("execution_orders.id")),sa.Column("live_position_id",sa.Integer,sa.ForeignKey("live_positions.id")),sa.Column("message",sa.String(1000),nullable=False),sa.Column("metadata_json",sa.JSON,nullable=False),sa.Column("created_at",TS,nullable=False))
    op.create_index("ix_execution_events_event_type","execution_events",["event_type"]); op.create_index("ix_execution_events_created_at","execution_events",["created_at"])
    op.create_table("daily_risk_ledgers",sa.Column("id",sa.Integer,primary_key=True),sa.Column("trading_date",TS,nullable=False),sa.Column("exchange",sa.String(32),nullable=False),sa.Column("environment",sa.String(16),nullable=False),sa.Column("starting_equity",P,nullable=False),sa.Column("current_equity",P,nullable=False),sa.Column("realized_pnl",P,nullable=False),sa.Column("unrealized_pnl",P,nullable=False),sa.Column("loss_pct",sa.Numeric(8,4),nullable=False),sa.Column("orders_submitted",sa.Integer,nullable=False),sa.Column("trades_opened",sa.Integer,nullable=False),sa.Column("trades_closed",sa.Integer,nullable=False),sa.Column("kill_switch_triggered",sa.Boolean,nullable=False),*timestamps(),sa.UniqueConstraint("trading_date","exchange","environment",name="uq_daily_risk_ledger"))
def downgrade():
    for table in ("daily_risk_ledgers","execution_events","execution_fills","live_positions","execution_orders","exchange_accounts"): op.drop_table(table)
