import { useEffect, useState } from 'react'
import { api } from '../api'
import { formatDisplayValue, formatNumber } from '../format'

const label=value=>String(value||'unknown').replaceAll('_',' ')
const money=value=>value===null||value===undefined?'Unavailable':`$${Number(value).toFixed(2)}`
const Badge=({value})=><span className={`bot-badge ${value==='protected'?'good':value==='unprotected'||value==='protection_failed'?'bad':'warn'}`}>{label(value)}</span>

export default function ActiveTrades(){
  const [positions,setPositions]=useState([]),[protections,setProtections]=useState({}),[detail,setDetail]=useState(null),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('')
  const load=async()=>{const {data}=await api.get('/execution/positions');setPositions(data);const rows=await Promise.all(data.filter(x=>x.status!=='closed').map(async x=>[x.id,(await api.get(`/execution/positions/${x.id}/protection`)).data]));setProtections(Object.fromEntries(rows))}
  const reconcile=async()=>{setRefreshing(true);setError('');try{await api.post('/execution/reconcile');await load()}catch(e){setError(e.response?.data?.detail||'Binance reconciliation failed')}finally{setRefreshing(false)}}
  useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[])
  const active=positions.filter(x=>x.status!=='closed')
  const aggregate=active.every(x=>x.unrealized_pnl!==null)?active.reduce((sum,x)=>sum+Number(x.unrealized_pnl),0):null
  return <><div className="page-head"><div><p className="eyebrow">AUTOMATED SPOT CONTROL</p><h1>Active Trades</h1><p className="subhead">Protection is confirmed only by acknowledged Binance Spot Testnet orders.</p></div><button disabled={refreshing} onClick={reconcile}>{refreshing?'Reconciling…':'Refresh from Binance'}</button></div>{error&&<p className="critical">{error}</p>}<section className="bot-metrics"><div className="metric"><span>Open positions</span><strong>{active.length}</strong></div><div className="metric"><span>Protected</span><strong>{active.filter(x=>x.protection_status==='protected').length}</strong></div><div className="metric"><span>Unprotected</span><strong>{active.filter(x=>x.protection_status!=='protected').length}</strong></div><div className="metric"><span>Unrealized PnL</span><strong>{money(aggregate)}</strong></div></section>{active.length?<div className="trade-cards">{active.map(x=>{const protection=protections[x.id]?.[0];return <article key={x.id} onClick={()=>setDetail({position:x,protection})}><div className="trade-top"><h3>Position #{x.id}</h3><Badge value={x.protection_status||'unprotected'}/></div>{x.protection_status!=='protected'&&<p className="critical">CRITICAL: Position does not have confirmed exchange protection.</p>}<dl className="trade-values"><dt>Current price</dt><dd>{formatNumber(x.current_price,8)}</dd><dt>Average entry</dt><dd>{formatNumber(x.average_entry,8)}</dd><dt>Quantity</dt><dd>{formatNumber(x.remaining_quantity,8)}</dd><dt>Market value</dt><dd>{money(x.market_value)}</dd><dt>Cost basis</dt><dd>{money(x.cost_basis)}</dd><dt>Unrealized PnL</dt><dd>{money(x.unrealized_pnl)}</dd><dt>Unrealized PnL %</dt><dd>{x.unrealized_pnl_pct===null?'Unavailable':`${Number(x.unrealized_pnl_pct).toFixed(2)}%`}</dd><dt>Protection</dt><dd>{label(x.protection_status)}</dd><dt>Last reconciled</dt><dd>{x.last_reconciled_at?new Date(x.last_reconciled_at).toLocaleString():'Never'}</dd></dl></article>})}</div>:<div className="friendly-empty">The bot currently has no open Binance positions.</div>}{detail&&<div className="drawer-backdrop" onClick={()=>setDetail(null)}><aside className="trade-drawer" onClick={e=>e.stopPropagation()}><button onClick={()=>setDetail(null)}>Close</button><h2>Position #{detail.position.id}</h2><Badge value={detail.position.protection_status}/><dl className="config-list">{Object.entries(detail.position).map(([k,v])=><span key={k}><dt>{label(k)}</dt><dd>{formatDisplayValue(v)}</dd></span>)}</dl><h3>Exchange protection</h3>{detail.protection?<dl className="config-list">{Object.entries(detail.protection).filter(([k])=>k!=='raw_status_json').map(([k,v])=><span key={k}><dt>{label(k)}</dt><dd>{formatDisplayValue(v)}</dd></span>)}</dl>:<p className="critical">No protective Binance order list is persisted.</p>}</aside></div>}</>
}
