import { useEffect, useState } from 'react'
import { api } from '../api'
import { formatDisplayValue, formatNumber } from '../format'

const label=value=>String(value||'unknown').replaceAll('_',' ')
const Badge=({value})=><span className={`bot-badge ${value==='protected'?'good':value==='unprotected'||value==='protection_failed'?'bad':'warn'}`}>{label(value)}</span>

export default function ActiveTrades(){
  const [positions,setPositions]=useState([]),[protections,setProtections]=useState({}),[detail,setDetail]=useState(null)
  const load=async()=>{const {data}=await api.get('/execution/positions');setPositions(data);const rows=await Promise.all(data.filter(x=>x.status!=='closed').map(async x=>[x.id,(await api.get(`/execution/positions/${x.id}/protection`)).data]));setProtections(Object.fromEntries(rows))}
  useEffect(()=>{load()},[])
  const active=positions.filter(x=>x.status!=='closed')
  return <><div className="page-head"><div><p className="eyebrow">AUTOMATED SPOT CONTROL</p><h1>Active Trades</h1><p className="subhead">Protection is confirmed only by acknowledged Binance Spot Testnet orders.</p></div><button onClick={load}>Refresh from Binance</button></div><section className="bot-metrics"><div className="metric"><span>Open positions</span><strong>{active.length}</strong></div><div className="metric"><span>Protected</span><strong>{active.filter(x=>x.protection_status==='protected').length}</strong></div><div className="metric"><span>Unprotected</span><strong>{active.filter(x=>x.protection_status!=='protected').length}</strong></div></section>{active.length?<div className="trade-cards">{active.map(x=>{const protection=protections[x.id]?.[0];return <article key={x.id} onClick={()=>setDetail({position:x,protection})}><div className="trade-top"><h3>Position #{x.id}</h3><Badge value={x.protection_status||'unprotected'}/></div>{x.protection_status!=='protected'&&<p className="critical">CRITICAL: Position does not have confirmed exchange protection.</p>}<dl className="trade-values"><dt>Average entry</dt><dd>{formatNumber(x.average_entry,8)}</dd><dt>Quantity</dt><dd>{formatNumber(x.remaining_quantity,8)}</dd><dt>Stop loss</dt><dd>{formatNumber(x.stop_loss,8)}</dd><dt>TP1</dt><dd>{formatNumber(x.take_profit_1,8)}</dd><dt>Order list</dt><dd>{protection?.order_list_id||'None acknowledged'}</dd></dl><div className="trade-progress"><i className="done">Entry filled</i><i className={x.protection_status==='protected'?'done':''}>Exchange protected</i><i>Closed</i></div></article>})}</div>:<div className="friendly-empty">The bot currently has no open Binance positions.</div>}{detail&&<div className="drawer-backdrop" onClick={()=>setDetail(null)}><aside className="trade-drawer" onClick={e=>e.stopPropagation()}><button onClick={()=>setDetail(null)}>Close</button><h2>Position #{detail.position.id}</h2><Badge value={detail.position.protection_status}/><h3>Position</h3><dl className="config-list">{Object.entries(detail.position).map(([k,v])=><span key={k}><dt>{label(k)}</dt><dd>{formatDisplayValue(v)}</dd></span>)}</dl><h3>Exchange protection</h3>{detail.protection?<dl className="config-list">{Object.entries(detail.protection).filter(([k])=>k!=='raw_status_json').map(([k,v])=><span key={k}><dt>{label(k)}</dt><dd>{formatDisplayValue(v)}</dd></span>)}</dl>:<p className="critical">No protective Binance order list is persisted.</p>}</aside></div>}</>
}
