import { useEffect, useState } from 'react'
import { Activity, Bell, Crosshair, Layers3, Radio, ShieldCheck, Target, TrendingUp } from 'lucide-react'
import { api } from '../api'

const Card = ({ icon: Icon, label, value, tone = '' }) => <div className={`status-card ${tone}`}><Icon/><span>{label}</span><strong>{value ?? '—'}</strong></div>

export default function Dashboard({navigate}) {
  const [health,setHealth]=useState(null), [symbol,setSymbol]=useState('BTCUSDT'), [data,setData]=useState({})
  useEffect(()=>{api.get('/health').then(r=>setHealth(r.data))},[])
  useEffect(()=>{const p={symbol,timeframe:'1h'},safe=x=>x.catch(()=>({data:null}));Promise.all([safe(api.get('/market-bias',{params:{symbol}})),safe(api.get('/structure-score',{params:p})),api.get('/structure',{params:p}),api.get('/fvg',{params:p}),api.get('/order-blocks',{params:p}),api.get('/liquidity',{params:p}),api.get('/alerts',{params:{symbol,limit:5}}),api.get('/candles',{params:{...p,limit:1}})]).then(([bias,score,structure,fvg,blocks,liquidity,alerts,candles])=>setData({bias:bias.data,score:score.data,structure:structure.data,fvg:fvg.data,blocks:blocks.data,liquidity:liquidity.data,alerts:alerts.data,lastPrice:+candles.data.at(-1)?.close}))},[symbol])
  const latest = type => [...(data.structure||[])].reverse().find(x=>x.event_type===type)
  const activeFvg=(data.fvg||[]).filter(x=>['active','partially_mitigated'].includes(x.status)).length
  const activeBlocks=(data.blocks||[]).filter(x=>['active','partially_mitigated'].includes(x.status)).length
  const nearest=(data.liquidity||[]).filter(x=>!x.swept_at).sort((a,b)=>Math.abs(+a.price-data.lastPrice)-Math.abs(+b.price-data.lastPrice))[0]
  const tone=data.score?.score>=70?'bullish':data.score?.score<50?'bearish':'neutral'
  return <><div className="page-head"><div><p className="eyebrow">PHASE 2 · SMART MONEY CONCEPTS</p><h1>Command Center</h1><p className="subhead">Top-down structure, liquidity and institutional price-delivery context.</p></div><select value={symbol} onChange={e=>setSymbol(e.target.value)}><option>BTCUSDT</option><option>ETHUSDT</option></select></div><div className="hero-grid"><section className={`panel hero bias-${tone}`}><span className="kicker">MARKET BIAS · {symbol}</span><h2>{data.bias?.label || 'Building multi-timeframe context…'}</h2><p className="bias-detail">H4 {data.bias?.timeframes?.['4h'] || '—'} · H1 {data.bias?.timeframes?.['1h'] || '—'} · M15 {data.bias?.timeframes?.['15m'] || '—'}</p><button onClick={()=>navigate('analysis')}>Open SMC analysis →</button></section><div className="status-stack"><Card icon={TrendingUp} label="Structure score" value={data.score ? `${data.score.score} · ${data.score.label}` : null} tone={tone}/><Card icon={Radio} label="Market stream" value={health?.market_stream?.connected?'live':'reconnecting'}/><Card icon={ShieldCheck} label="Analysis" value={health?.status||'checking'}/><Card icon={Bell} label="Recent alerts" value={data.alerts?.length}/></div></div><div className="smc-cards"><Card icon={Activity} label="Latest BOS" value={latest('BOS')?.direction}/><Card icon={Crosshair} label="Latest CHoCH" value={latest('CHoCH')?.direction}/><Card icon={Layers3} label="Active FVG" value={activeFvg}/><Card icon={Target} label="Active order blocks" value={activeBlocks}/><Card icon={Crosshair} label="Nearest liquidity" value={nearest ? `${nearest.type} · ${nearest.price}` : null}/></div><section className="panel safety"><p className="eyebrow">LATEST ALERTS</p>{data.alerts?.length ? data.alerts.map(alert=><p key={alert.id}>{alert.type} · {alert.message}</p>) : <p>No SMC alerts yet.</p>}</section></>
}
