import { useEffect, useState } from 'react'
import { api } from '../api'

const format = value => value == null ? '—' : typeof value === 'string' && value.includes('T') ? new Date(value).toLocaleString() : value
const Table = ({ columns, rows }) => <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key}>{format(r[c.key])}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">No records yet. Data appears after closed candles are analyzed.</p>}</div>
const Filters = ({symbol,setSymbol,timeframe,setTimeframe}) => <div className="controls"><select value={symbol} onChange={e=>setSymbol(e.target.value)}><option>BTCUSDT</option><option>ETHUSDT</option></select><select value={timeframe} onChange={e=>setTimeframe(e.target.value)}><option>15m</option><option>1h</option><option>4h</option></select></div>

export function StructureEvents(){const [s,setS]=useState('BTCUSDT'),[t,setT]=useState('1h'),[rows,setRows]=useState([]);useEffect(()=>{api.get('/structure',{params:{symbol:s,timeframe:t}}).then(r=>setRows(r.data))},[s,t]);return <><div className="page-head"><div><p className="eyebrow">STRUCTURE TAPE</p><h1>Structure Events</h1></div><Filters symbol={s} setSymbol={setS} timeframe={t} setTimeframe={setT}/></div><section className="panel"><Table rows={rows} columns={[{key:'detected_at',label:'Detected'},{key:'event_type',label:'Event'},{key:'direction',label:'Direction'},{key:'previous_trend',label:'From'},{key:'resulting_trend',label:'To'},{key:'break_price',label:'Break price'},{key:'confidence',label:'Confidence'}]}/></section></>}
export function FVGZones(){const [s,setS]=useState('BTCUSDT'),[t,setT]=useState('1h'),[rows,setRows]=useState([]);useEffect(()=>{api.get('/fvg',{params:{symbol:s,timeframe:t}}).then(r=>setRows(r.data))},[s,t]);return <><div className="page-head"><div><p className="eyebrow">IMBALANCE MAP</p><h1>Fair Value Gaps</h1></div><Filters symbol={s} setSymbol={setS} timeframe={t} setTimeframe={setT}/></div><section className="panel"><Table rows={rows} columns={[{key:'detected_at',label:'Detected'},{key:'direction',label:'Direction'},{key:'lower_price',label:'Lower'},{key:'upper_price',label:'Upper'},{key:'size_percentage',label:'Size %'},{key:'status',label:'Status'},{key:'mitigation_percentage',label:'Mitigated %'}]}/></section></>}
export function SystemLogs(){const [rows,setRows]=useState([]);useEffect(()=>{api.get('/logs',{params:{limit:500}}).then(r=>setRows(r.data))},[]);return <><div className="page-head"><div><p className="eyebrow">OPERATIONS</p><h1>System Logs</h1></div></div><section className="panel"><Table rows={rows} columns={[{key:'created_at',label:'Time'},{key:'level',label:'Level'},{key:'service',label:'Service'},{key:'event_type',label:'Event'},{key:'message',label:'Message'}]}/></section></>}

