import {useEffect,useState} from 'react'
import {api} from '../api'
const fmt=v=>v??'—'
const Table=({rows,fields})=><div className="table-wrap"><table><thead><tr>{fields.map(x=><th key={x}>{x.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{fields.map(f=><td key={f}>{fmt(r[f])}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">No records.</p>}</div>
const Head=({title,sub})=><div className="page-head"><div><p className="eyebrow">BINANCE SPOT EXECUTION</p><h1>{title}</h1><p className="subhead">{sub}</p></div></div>
export function ExecutionCenter(){const [s,setS]=useState({});useEffect(()=>{api.get('/execution/status').then(r=>setS(r.data))},[]);return <><Head title="Execution Center" sub="Testnet-first deterministic execution status."/><div className={`execution-banner ${s.environment==='production'?'danger':''}`}><strong>{(s.environment||'testnet').toUpperCase()}</strong><span>{s.production_locked?'PRODUCTION LOCKED':'Execution configured'}</span></div><section className="metrics">{[['Mode',s.mode],['Execution',s.enabled?'ENABLED':'DISABLED'],['Account',s.connected?'Connected':'Disconnected'],['API key',s.masked_api_key],['Kill switch',s.kill_switch?'ON':'OFF']].map(([a,b])=><div className="metric" key={a}><span>{a}</span><strong>{fmt(b)}</strong></div>)}</section><section className="panel"><div className="panel-title">Safety boundary</div><p>Spot only. No withdrawals, transfers, margin, futures, leverage, or short selling. Orders require deterministic risk approval and explicit confirmation.</p></section></>}
export function ApprovalQueue(){const [rows,setRows]=useState([]);useEffect(()=>{api.get('/execution/approval-queue').then(r=>setRows(r.data))},[]);return <><Head title="Approval Queue" sub="Eligible deterministic setups awaiting administrator approval."/><Table rows={rows} fields={['id','strategy','direction','setup_timeframe','confidence_score','preferred_entry','stop_loss','take_profit_1','expires_at','status']}/><p className="safety-copy">Approval and submission require authenticated administrator access and Testnet confirmation.</p></>}
export function ExchangeOrders(){const [rows,setRows]=useState([]);useEffect(()=>{api.get('/execution/orders').then(r=>setRows(r.data))},[]);return <><Head title="Exchange Orders" sub="Persisted and reconciled Binance order state."/><Table rows={rows} fields={['id','client_order_id','side','order_type','requested_quantity','executed_quantity','status','execution_state']}/></>}
export function LivePositions(){const [rows,setRows]=useState([]);useEffect(()=>{api.get('/execution/positions').then(r=>setRows(r.data))},[]);return <><Head title="Live Positions" sub="Spot positions and protected remaining quantities."/><Table rows={rows} fields={['id','direction','status','base_quantity','remaining_quantity','average_entry','stop_loss','realized_pnl','total_fees']}/></>}
export function AccountBalances(){const [s,setS]=useState({});useEffect(()=>{api.get('/execution/status').then(r=>setS(r.data))},[]);return <><Head title="Account & Balances" sub="Secrets never leave the backend."/><section className="panel"><p>Account: {s.connected?'Connected':'Not connected'}</p><p>Masked API key: {fmt(s.masked_api_key)}</p><p>Environment: {(s.environment||'testnet').toUpperCase()}</p></section></>}
export function RiskControl(){const [r,setR]=useState({});useEffect(()=>{api.get('/execution/risk').then(x=>setR(x.data))},[]);return <><Head title="Risk Control" sub="Hard limits applied before every submission."/><section className="metrics">{Object.entries(r).map(([k,v])=><div className="metric" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{String(v)}</strong></div>)}</section><div className="execution-banner danger"><strong>KILL SWITCH</strong><span>Changing this state requires authenticated administrator access.</span></div></>}
