import { useEffect, useState } from 'react'
import { api } from '../api'
import { formatDisplayValue, formatNumber } from '../format'

const Safety = () => <div className="paper-banner"><strong>PAPER ANALYSIS ONLY</strong><span>NO LIVE ORDER EXECUTION · Setups express deterministic bias and confidence, never guaranteed profit.</span></div>
const Cell = ({value,numeric=false}) => <td>{numeric?formatNumber(value):formatDisplayValue(value)}</td>

export function LiquiditySweeps(){const [symbol,setSymbol]=useState('BTCUSDT'),[timeframe,setTimeframe]=useState('15m'),[rows,setRows]=useState([]);useEffect(()=>{api.get('/liquidity-sweeps',{params:{symbol,timeframe,limit:500}}).then(r=>setRows(r.data))},[symbol,timeframe]);return <><div className="page-head"><div><p className="eyebrow">LIQUIDITY ENGINE</p><h1>Liquidity Sweeps</h1></div><div className="controls"><select value={symbol} onChange={e=>setSymbol(e.target.value)}><option>BTCUSDT</option><option>ETHUSDT</option></select><select value={timeframe} onChange={e=>setTimeframe(e.target.value)}><option>15m</option><option>1h</option><option>4h</option></select></div></div><Safety/><section className="panel table-wrap"><table><thead><tr>{['Detected','Direction','Type','Liquidity','Extreme','Reclaim','Status','Confidence','Pool'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><Cell value={row.detected_at}/><Cell value={row.direction}/><Cell value={row.sweep_type}/><Cell value={row.liquidity_price} numeric/><Cell value={row.extreme_price} numeric/><Cell value={row.reclaimed_price} numeric/><Cell value={row.status}/><Cell value={row.confidence_score} numeric/><Cell value={row.liquidity_pool_id}/></tr>)}</tbody></table>{!rows.length&&<p className="empty">No causal liquidity sweeps detected yet.</p>}</section></>}

export function TradeSetups(){const [symbol,setSymbol]=useState('BTCUSDT'),[rows,setRows]=useState([]),[selected,setSelected]=useState(null);useEffect(()=>{api.get('/trade-setups',{params:{symbol,limit:500}}).then(r=>setRows(r.data))},[symbol]);return <><div className="page-head"><div><p className="eyebrow">DETERMINISTIC OPPORTUNITIES</p><h1>Trade Setups</h1></div><select value={symbol} onChange={e=>setSymbol(e.target.value)}><option>BTCUSDT</option><option>ETHUSDT</option></select></div><Safety/><section className="panel table-wrap"><table><thead><tr>{['Direction','Strategy','Status','Entry Zone','Preferred','SL','TP1','TP2','TP3','R:R 2','Confidence','Expires'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} onClick={()=>setSelected(row)} className="clickable"><Cell value={row.direction}/><Cell value={row.strategy}/><Cell value={row.status}/><td>{formatNumber(row.entry_min)}–{formatNumber(row.entry_max)}</td><Cell value={row.preferred_entry} numeric/><Cell value={row.stop_loss} numeric/><Cell value={row.take_profit_1} numeric/><Cell value={row.take_profit_2} numeric/><Cell value={row.take_profit_3} numeric/><Cell value={row.risk_reward_2} numeric/><Cell value={row.confidence_score} numeric/><Cell value={row.expires_at}/></tr>)}</tbody></table>{!rows.length&&<p className="empty">No paper-analysis setups satisfy the deterministic rules yet.</p>}</section>{selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="setup-drawer" onClick={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)}>Close ×</button><p className="eyebrow">PAPER ANALYSIS ONLY</p><h2>{selected.strategy.replaceAll('_',' ')}</h2><div className="drawer-grid"><span>Confidence<strong>{formatNumber(selected.confidence_score)}</strong></span><span>Status<strong>{selected.status}</strong></span><span>Liquidity sweep<strong>#{selected.liquidity_sweep_id||'—'}</strong></span><span>Structure event<strong>#{selected.structure_event_id}</strong></span><span>FVG<strong>#{selected.fvg_zone_id||'—'}</strong></span><span>Order block<strong>#{selected.order_block_id||'—'}</strong></span></div><h3>Score breakdown</h3><pre>{JSON.stringify(selected.score_breakdown_json,null,2)}</pre><h3>Conditions</h3><pre>{JSON.stringify(selected.setup_conditions_json,null,2)}</pre>{selected.rejection_reasons_json.length>0&&<><h3>Rejection reasons</h3><ul>{selected.rejection_reasons_json.map(reason=><li key={reason}>{reason}</li>)}</ul></>}<p className="safety-copy">No exchange order can be submitted from this screen.</p></aside></div>}</>}
