import {useEffect,useState} from 'react'
import {api} from '../api'

const money=v=>`$${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`
const number=(v,d=2)=>v==null?'—':Number(v).toFixed(d)
const Metrics=({items})=><div className="summary-grid">{items.map(([k,v])=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>
const AggregateTable=({title,rows})=><section className="panel"><div className="panel-title">{title}</div><div className="table-wrap"><table><thead><tr><th>Group</th><th>Trades</th><th>Wins / Losses</th><th>Win rate</th><th>Net R</th><th>Profit factor</th><th>Expectancy</th><th>Max DD</th></tr></thead><tbody>{rows.map(x=><tr key={x.value}><td>{x.value}</td><td>{x.total_trades}</td><td>{x.wins} / {x.losses}</td><td>{number(x.win_rate,1)}%</td><td>{number(x.net_r)}</td><td>{number(x.profit_factor)}</td><td>{number(x.expectancy)} R</td><td>{number(x.max_drawdown_r)} R</td></tr>)}</tbody></table></div></section>

export default function StrategyPerformance(){
  const [filters,setFilters]=useState({symbol:'',strategy:'',timeframe:'',confidence_min:50,confidence_max:100,start:'',end:''})
  const [data,setData]=useState({summary:{},trades:[],strategies:[],confidence:[],timeframes:[],compare:[],wave3:[],components:[]}),[error,setError]=useState(''),[audit,setAudit]=useState(null)
  const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,(k==='start'||k==='end')?new Date(`${v}:00Z`).toISOString():v]))
  const load=()=>{setError('');Promise.all(['/summary','/trades','/strategies','/confidence','/timeframes','/compare-testnet','/wave3-ha/signals','/wave3-ha/components'].map(path=>api.get(`/paper-forward${path}`,{params}))).then(([summary,trades,strategies,confidence,timeframes,compare,wave3,components])=>setData({summary:summary.data,trades:trades.data,strategies:strategies.data,confidence:confidence.data,timeframes:timeframes.data,compare:compare.data,wave3:wave3.data,components:components.data})).catch(e=>setError(e.response?.data?.detail||e.message))}
  useEffect(()=>{load()},[])
  const change=e=>setFilters({...filters,[e.target.name]:e.target.value})
  const s=data.summary
  return <div><div className="production-paper-banner"><strong>PRODUCTION MARKET DATA</strong><span>Strategy simulation only · Binance Testnet fills are excluded from performance</span></div><div className="page-head"><div><p className="eyebrow">TRUSTWORTHY FORWARD MEASUREMENT</p><h1>Strategy Performance</h1><p className="subhead">Canonical TradeSetup geometry evaluated against persisted Binance Production Spot candles.</p></div></div>
    <section className="panel performance-filters">{[['symbol','Symbol'],['strategy','Strategy'],['timeframe','Timeframe'],['confidence_min','Confidence min'],['confidence_max','Confidence max'],['start','Start'],['end','End']].map(([name,label])=><label key={name}>{label}<input name={name} type={name==='start'||name==='end'?'datetime-local':name.startsWith('confidence')?'number':'text'} value={filters[name]} onChange={change}/></label>)}<button className="primary" onClick={load}>Apply filters</button></section>{error&&<div className="alert">{String(error)}</div>}
    <Metrics items={[["Total trades",s.total_trades||0],["Wins",s.wins||0],["Losses",s.losses||0],["Win rate",`${number(s.win_rate,1)}%`],["Net PnL",money(s.net_pnl)],["Profit factor",number(s.profit_factor)],["Expectancy",`${number(s.expectancy)} R`],["Average R",number(s.average_r)],["Max drawdown",`${number(s.max_drawdown_r)} R`],["Consecutive losses",s.consecutive_losses||0],["Average holding",`${number((s.average_holding_seconds||0)/3600,1)}h`],["Ambiguous excluded",s.ambiguous_excluded||0]]}/>
    <AggregateTable title="By strategy" rows={data.strategies}/><AggregateTable title="By confidence bucket" rows={data.confidence}/><AggregateTable title="By timeframe" rows={data.timeframes}/>
    <section className="panel"><div className="panel-title">Wave-3 Heikin Ashi Research <small>Research only · live automatic execution disabled</small></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Variant</th><th>Side</th><th>Score</th><th>Real entry / SL</th><th>Exit</th><th>R</th><th>MFE / MAE</th></tr></thead><tbody>{data.wave3.map(x=><tr key={x.id} className="clickable" onClick={()=>setAudit(x)}><td>{x.decision_time}</td><td>{x.variant}</td><td>{x.direction}</td><td>{number(x.score,0)}</td><td>{x.real_entry} / {x.real_stop}</td><td>{x.exit_reason||'—'} · {x.real_exit||'—'}</td><td>{number(x.realized_r)}</td><td>{number(x.mfe_r)} / {number(x.mae_r)}</td></tr>)}</tbody></table></div>{audit&&<div className="setup-drawer"><button onClick={()=>setAudit(null)}>Close ×</button><h3>Signal audit</h3><pre>{JSON.stringify({elliott_count_id:audit.elliott_count_id,wave_point_ids:audit.wave_point_ids_json,artifacts:audit.artifact_ids_json,score:audit.score_components_json,entry:audit.audit_json,exit_ha_candle_id:audit.exit_ha_candle_id,market_data_source:audit.market_data_source},null,2)}</pre></div>}</section>
    <section className="panel"><div className="panel-title">Wave-3 HA results by confluence component</div><div className="table-wrap"><table><thead><tr><th>Component</th><th>Trades</th><th>Wins / Losses</th><th>Win rate</th><th>Net R</th><th>Average R</th><th>Profit factor</th></tr></thead><tbody>{data.components.map(x=><tr key={x.component}><td>{x.component}</td><td>{x.total_trades}</td><td>{x.wins} / {x.losses}</td><td>{number(x.win_rate,1)}%</td><td>{number(x.net_r)}</td><td>{number(x.average_r)}</td><td>{number(x.profit_factor)}</td></tr>)}</tbody></table></div></section>
    <section className="panel"><div className="panel-title">Paper Forward Trades</div><div className="table-wrap"><table><thead><tr><th>Setup</th><th>Symbol</th><th>Strategy</th><th>TF</th><th>Confidence</th><th>Status</th><th>Exit reason</th><th>PnL</th><th>R</th><th>MFE / MAE</th></tr></thead><tbody>{data.trades.map(x=><tr key={x.id}><td>{x.setup_id}</td><td>{x.symbol}</td><td>{x.strategy}</td><td>{x.timeframe}</td><td>{number(x.confidence_score,0)}</td><td>{x.status}{x.is_ambiguous?' *':''}</td><td>{x.exit_reason||'—'}</td><td>{money(x.realized_pnl)}</td><td>{number(x.realized_r)}</td><td>{number(x.mfe_r)} / {number(x.mae_r)} R</td></tr>)}</tbody></table></div><p className="subhead">* Same-candle SL/TP ambiguity: stop-first; excluded from headline win rate.</p></section>
    <section className="panel testnet-comparison"><div className="panel-title">Compare with Testnet <small>Execution-quality diagnostic only — never combined with paper-forward PnL</small></div><div className="table-wrap"><table><thead><tr><th>Setup ID</th><th>Paper production-market result</th><th>Testnet execution result</th><th>Intended SL</th><th>Testnet actual exit</th><th>Testnet slippage</th><th>Difference in R</th></tr></thead><tbody>{data.compare.map(x=><tr key={x.setup_id}><td>{x.setup_id}</td><td>{x.paper_result.exit_reason||x.paper_result.status} · {number(x.paper_result.realized_r)} R</td><td>{x.testnet_result?`${x.testnet_result.exit_reason||x.testnet_result.status} · ${money(x.testnet_result.realized_pnl)}`:'No Testnet position'}</td><td>{x.intended_sl}</td><td>{x.testnet_actual_exit||'—'}</td><td>{x.testnet_slippage==null?'—':money(x.testnet_slippage)}</td><td>{number(x.difference_in_r)}</td></tr>)}</tbody></table></div></section>
  </div>
}
