import { useEffect, useState } from 'react'
import { api } from '../api'

const money = value => `$${Number(value || 0).toLocaleString(undefined,{maximumFractionDigits:2})}`
const Metrics = ({items}) => <div className="summary-grid">{items.map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value ?? '—'}</strong></div>)}</div>
const TradeTable=({rows})=><section className="panel"><div className="panel-title">Trades</div><div className="table-wrap"><table><thead><tr><th>Entry</th><th>Direction</th><th>Exit</th><th>Reason</th><th>PnL</th><th>R</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.entry_time).toLocaleString()}</td><td>{x.direction}</td><td>{x.exit_price}</td><td>{x.exit_reason}</td><td>{money(x.realized_pnl)}</td><td>{Number(x.realized_r).toFixed(2)}</td></tr>)}</tbody></table></div></section>

const ReplayDiagnostics=({run})=>{
  const diagnostics=run.settings_json?.diagnostics||{}
  const reasons=Object.entries(diagnostics.rejection_reasons||{}).sort((a,b)=>b[1]-a[1]).slice(0,8)
  return <><section className="panel"><div className="panel-title">Replay Diagnostics</div><Metrics items={[
    ['Candles processed',diagnostics.candles_processed],['Setup candidates',diagnostics.setup_candidates],
    ['Rejected setups',diagnostics.setups_rejected],['Eligible setups',diagnostics.setups_eligible],
    ['Entries triggered',diagnostics.entries_triggered],['Trades opened',diagnostics.trades_opened],
    ['Trades closed',diagnostics.trades_closed],
  ]}/>{reasons.length>0&&<div className="table-wrap"><table><thead><tr><th>Top rejection reason</th><th>Count</th><th>Percentage</th></tr></thead><tbody>{reasons.map(([reason,count])=><tr key={reason}><td>{reason.replaceAll('_',' ')}</td><td>{count}</td><td>{diagnostics.setup_candidates?`${(count/diagnostics.setup_candidates*100).toFixed(1)}%`:'0%'}</td></tr>)}</tbody></table></div>}</section></>
}

export function Backtests(){
  const [form,setForm]=useState({symbol:'BTCUSDT',timeframe:'1h',strategy:'ALL',start_time:'2025-01-01T00:00',end_time:'2025-12-31T00:00',starting_balance:10000,risk_per_trade_pct:1,taker_fee_pct:.05,slippage_bps:2,same_candle_policy:'stop_first'})
  const [runs,setRuns]=useState([]),[selected,setSelected]=useState(null),[trades,setTrades]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preparation,setPreparation]=useState(null)
  const load=()=>api.get('/backtests').then(r=>setRuns(r.data))
  useEffect(()=>{load()},[])
  useEffect(()=>{if(!busy)return;const timer=setInterval(()=>api.get('/market-data/backfill/status',{params:{symbol:form.symbol,timeframe:form.timeframe}}).then(r=>setPreparation(r.data)).catch(()=>{}),1000);return()=>clearInterval(timer)},[busy,form.symbol,form.timeframe])
  const run=async()=>{setBusy(true);setError('');try{const {data}=await api.post('/backtests',{...form,start_time:new Date(form.start_time).toISOString(),end_time:new Date(form.end_time).toISOString()},{timeout:600000});setSelected(data);setTrades((await api.get(`/backtests/${data.id}/trades`)).data);load()}catch(e){const detail=e.response?.data?.detail;setError(typeof detail==='string'?detail:detail?.message||e.message)}finally{setBusy(false)}}
  const show=async item=>{const {data}=await api.get(`/backtests/${item.id}`);setSelected(data);setTrades((await api.get(`/backtests/${item.id}/trades`)).data)}
  return <div><div className="page-head"><div><p className="eyebrow">DETERMINISTIC REPLAY</p><h1>Backtests</h1><p className="subhead">Closed-candle, no-look-ahead simulation with explicit costs.</p></div></div>
    {error&&<div className="alert">{error}</div>}{busy&&<div className="alert">Preparing historical market data… {preparation?.status==='running'&&`Fetched ${preparation.inserted_candles+preparation.updated_candles} / ${preparation.inserted_candles+preparation.updated_candles+preparation.remaining_estimate} candles.`} The replay will start automatically when coverage is ready.</div>}<section className="panel trading-form">{['symbol','timeframe','strategy','start_time','end_time','starting_balance','risk_per_trade_pct','taker_fee_pct','slippage_bps'].map(k=><label key={k}><span>{k.replaceAll('_',' ')}</span><input type={k.includes('time')&&k!=='timeframe'?'datetime-local':k.includes('balance')||k.includes('pct')||k.includes('bps')?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button onClick={run} disabled={busy}>{busy?'Preparing market data…':'Run Backtest'}</button></section>
    {selected&&<><section className="panel"><div className="panel-title">Backtest Summary</div><Metrics items={[['Starting Balance',money(selected.starting_balance)],['Ending Balance',money(Number(selected.starting_balance)+Number(selected.net_profit))],['Net PnL',money(selected.net_profit)],['Return %',`${Number(selected.settings_json?.results?.return_pct||0).toFixed(2)}%`],['Total Trades',selected.trades_taken],['Wins',selected.wins],['Losses',selected.losses],['Win Rate',`${Number(selected.win_rate).toFixed(1)}%`],['Profit Factor',selected.profit_factor?Number(selected.profit_factor).toFixed(2):'—'],['Expectancy',Number(selected.expectancy).toFixed(2)+' R'],['Average R',Number(selected.average_rr).toFixed(2)],['Maximum Drawdown',Number(selected.max_drawdown_pct).toFixed(2)+'%'],['Total Fees',money(selected.settings_json?.results?.total_fees)]]}/></section>{selected.trades_taken===0&&<div className="alert">No trades were executed during this replay. The diagnostics below show why.</div>}<ReplayDiagnostics run={selected}/><section className="panel"><div className="panel-title">Equity Curve</div><div className="equity-bars">{(selected.settings_json?.equity_curve||[]).map(x=><i key={x.index} style={{height:`${20+Math.max(0,80-x.drawdown_pct*4)}%`}} title={money(x.equity)}/>)}</div></section><section className="panel"><div className="panel-title">Drawdown Curve</div><div className="equity-bars">{(selected.settings_json?.drawdown_curve||[]).map(x=><i key={x.index} style={{height:`${Math.max(4,x.drawdown_pct*4)}%`}} title={`${money(x.drawdown)} / ${Number(x.drawdown_pct).toFixed(2)}%`}/>)}</div></section><TradeTable rows={trades}/></>}
    <section className="panel"><div className="panel-title">Recent runs</div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Strategy</th><th>Timeframe</th><th>Net PnL</th><th>Status</th></tr></thead><tbody>{runs.map(x=><tr key={x.id} onClick={()=>show(x)}><td>{x.id}</td><td>{x.strategy}</td><td>{x.timeframe}</td><td>{money(x.net_profit)}</td><td>{x.status}</td></tr>)}</tbody></table></div></section></div>
}

export function PaperTrading(){
  const [accounts,setAccounts]=useState([]),[positions,setPositions]=useState([]),[error,setError]=useState('')
  const load=()=>Promise.all([api.get('/paper/accounts'),api.get('/paper/positions')]).then(([a,p])=>{setAccounts(a.data);setPositions(p.data)})
  useEffect(()=>{load()},[])
  const account=accounts[0]
  const reset=async()=>{if(!account)return;setError('');try{await api.post(`/paper/accounts/${account.id}/reset`,{starting_balance:10000});load()}catch(e){setError(e.response?.data?.detail||e.message)}}
  const act=async(position)=>{setError('');try{const action=['waiting_entry','pending'].includes(position.status)?'cancel':'close';await api.post(`/paper/positions/${position.id}/${action}`,{});load()}catch(e){setError(e.response?.data?.detail||e.message)}}
  const active=positions.filter(x=>['waiting_entry','pending','open','partially_closed'].includes(x.status)),closed=positions.filter(x=>['closed','stopped'].includes(x.status))
  const table=rows=><div className="table-wrap"><table><thead><tr><th>Status</th><th>Direction</th><th>Entry</th><th>SL</th><th>TP1</th><th>TP2</th><th>TP3</th><th>PnL</th><th>Action</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.status}</td><td>{x.direction}</td><td>{x.entry_price}</td><td>{x.stop_loss}</td><td>{x.tp1}</td><td>{x.tp2}</td><td>{x.tp3}</td><td>{money(x.realized_pnl)}</td><td>{active.includes(x)&&<button onClick={()=>act(x)}>{['waiting_entry','pending'].includes(x.status)?'Cancel':'Paper close'}</button>}</td></tr>)}</tbody></table></div>
  return <div><div className="paper-banner">PAPER TRADING ONLY · NO LIVE FUNDS</div><div className="page-head"><div><p className="eyebrow">SIMULATED EXECUTION</p><h1>Paper Trading</h1></div><button onClick={reset}>Reset to $10,000</button></div>{error&&<div className="alert">{String(error)}</div>}<Metrics items={[['Balance',money(account?.balance)],['Equity',money(account?.equity)],['Realized PnL',money(account?.realized_pnl)],['Unrealized PnL',money(account?.unrealized_pnl)],['Current Drawdown',`${Number(account?.drawdown_pct||0).toFixed(2)}%`],['Available Risk',money(Number(account?.equity||0)*Number(account?.risk_per_trade_pct||1)/100)]]}/><section className="panel"><div className="panel-title">Open Positions</div>{table(active)}</section><section className="panel"><div className="panel-title">Recent Closed Trades</div>{table(closed)}</section></div>
}
export function Performance(){
  const [data,setData]=useState({})
  useEffect(()=>{api.get('/paper/performance').then(r=>setData(r.data))},[])
  return <div><div className="page-head"><div><p className="eyebrow">STRATEGY OBSERVATORY</p><h1>Performance</h1><p className="subhead">Calculated exclusively from closed paper trades.</p></div></div><Metrics items={[['Total Trades',data.total_trades],['Wins',data.wins],['Losses',data.losses],['Breakeven',data.breakeven],['Win Rate',`${Number(data.win_rate||0).toFixed(1)}%`],['Net PnL',money(data.net_pnl)],['Return %',`${Number(data.return_pct||0).toFixed(2)}%`],['Profit Factor',data.profit_factor?Number(data.profit_factor).toFixed(2):'—'],['Expectancy',Number(data.expectancy||0).toFixed(2)+' R'],['Average R',Number(data.average_r||0).toFixed(2)],['Max Drawdown',`${Number(data.max_drawdown_pct||0).toFixed(2)}%`]]}/>{Object.entries(data.breakdowns||{}).map(([name,rows])=><section className="panel" key={name}><div className="panel-title">By {name.replaceAll('_',' ')}</div><div className="table-wrap"><table><thead><tr><th>Group</th><th>Trades</th><th>Wins</th><th>Net PnL</th></tr></thead><tbody>{rows.map(row=><tr key={row.value}><td>{row.value}</td><td>{row.trades}</td><td>{row.wins}</td><td>{money(row.net_pnl)}</td></tr>)}</tbody></table></div></section>)}</div>
}
