import { useEffect, useState } from 'react'
import { api } from '../api'
import { formatDisplayValue, formatNumber } from '../format'

const money=value=>value===null||value===undefined?'Unavailable':`$${Number(value).toFixed(2)}`

export default function TradeHistory(){
  const [rows,setRows]=useState([]),[error,setError]=useState('')
  useEffect(()=>{api.get('/bot/trade-history').then(({data})=>setRows(data)).catch(e=>setError(e.response?.data?.detail||e.message))},[])
  const exportCsv=()=>{if(!rows.length)return;const keys=Object.keys(rows[0]);const csv=[keys.join(','),...rows.map(row=>keys.map(key=>`"${String(row[key]??'').replaceAll('"','""')}"`).join(','))].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='wavescope-trades.csv';link.click()}
  return <><div className="page-head"><div><p className="eyebrow">AUTOMATED SPOT CONTROL</p><h1>Trade History</h1><p className="subhead">Closed Binance positions remain auditable after reconciliation.</p></div><button onClick={exportCsv}>Export CSV</button></div>{error&&<div className="alert">{error}</div>}<section className="bot-metrics"><div className="metric"><span>Total trades</span><strong>{rows.length}</strong></div><div className="metric"><span>Net PnL</span><strong>{money(rows.reduce((sum,row)=>sum+Number(row.realized_pnl||0),0))}</strong></div><div className="metric"><span>Fees</span><strong>{money(rows.reduce((sum,row)=>sum+Number(row.fees||0),0))}</strong></div></section>{rows.length?<div className="panel table-wrap"><table><thead><tr><th>ID</th><th>Symbol</th><th>Strategy / TF</th><th>Direction</th><th>Opened</th><th>Entry</th><th>Quantity</th><th>Closed</th><th>Exit</th><th>PnL</th><th>PnL %</th><th>Fees</th><th>Exit reason</th><th>Protection</th></tr></thead><tbody>{rows.map(row=><tr key={row.position_id}><td>#{row.position_id}<br/><small>Setup #{row.setup_id}</small></td><td>{row.symbol}</td><td>{row.strategy}<br/><small>{row.timeframe}</small></td><td>{row.direction}</td><td>{formatDisplayValue(row.entry_time)}</td><td>{formatNumber(row.average_entry,8)}</td><td>{formatNumber(row.base_quantity,8)}</td><td>{formatDisplayValue(row.exit_time)}</td><td>{formatNumber(row.average_exit,8)}</td><td>{money(row.realized_pnl)}</td><td>{row.realized_pnl_pct==null?'Unavailable':`${Number(row.realized_pnl_pct).toFixed(2)}%`}</td><td>{money(row.fees)}</td><td>{row.exit_reason||'Unknown / external reconciliation'}</td><td>{row.protection_outcome}</td></tr>)}</tbody></table></div>:<div className="friendly-empty">No closed Binance positions are currently persisted.</div>}</>
}
