import {useEffect,useState} from 'react'
import {Activity,BarChart3,BookOpen,Bot,BrainCircuit,FlaskConical,History,KeyRound,LogOut,ScrollText,Shield,TrendingUp,WalletCards,Waves} from 'lucide-react'
import MarketAnalysis from './pages/MarketAnalysis'
import {SystemLogs} from './pages/DataPages'
import ElliottWave from './pages/ElliottWave'
import {Backtests,PaperTrading} from './pages/TradingPages'
import {BinanceConnection,BotDashboard,BotStrategies,RiskSettings} from './pages/ExecutionPages'
import ActiveTrades from './pages/ActiveTrades'
import TradeHistory from './pages/TradeHistory'
import {api} from './api'
import StrategyPerformance from './pages/StrategyPerformance'
import './trading.css'
const nav=[['dashboard','Dashboard',Bot],['connection','Binance Connection',KeyRound],['strategies','Bot Strategies',BrainCircuit],['active','Active Trades',Activity],['history','Trade History',History],['risk','Risk Settings',Shield],['performance','Strategy Performance',TrendingUp],['analysis','Market Analysis',BarChart3],['elliott','Elliott Wave',Waves],['backtests','Backtesting',FlaskConical],['paper','Paper Trading',WalletCards],['logs','System Logs',ScrollText]]
function Login({onLogin}){const [form,setForm]=useState({username:'',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const {data}=await api.post('/auth/login',form);onLogin(data.user)}catch(x){setError(x.response?.data?.detail||'Unable to sign in')}finally{setBusy(false)}};return <div className="login-page"><div className="login-brand"><div className="mark"><BookOpen size={23}/></div><div><strong>WaveScope</strong><small>PRIVATE BINANCE BOT CONTROL</small></div></div><form className="login-card" onSubmit={submit}><p className="eyebrow">SECURE ADMINISTRATOR ACCESS</p><h1>Welcome back</h1><p>Sign in to manage your Binance connection, strategies, risk controls and trading bot.</p>{error&&<div className="alert">{String(error)}</div>}<label>Username or email<input name="username" autoComplete="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})} required autoFocus/></label><label>Password<input name="password" type="password" autoComplete="current-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in to WaveScope'}</button><small>Private session · HttpOnly cookie · CSRF protected</small></form></div>}
export default function App(){const [page,setPage]=useState('dashboard'),[user,setUser]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{api.get('/auth/me',{timeout:8000}).then(r=>setUser(r.data)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[]);const logout=async()=>{try{await api.post('/auth/logout')}finally{setUser(null);setPage('dashboard')}};if(loading)return <div className="session-loader"><BookOpen size={28}/><span>Restoring secure session…</span></div>;if(!user)return <Login onLogin={setUser}/>;const pages={dashboard:<BotDashboard/>,connection:<BinanceConnection/>,strategies:<BotStrategies/>,active:<ActiveTrades/>,history:<TradeHistory/>,risk:<RiskSettings/>,performance:<StrategyPerformance/>,analysis:<MarketAnalysis/>,elliott:<ElliottWave/>,backtests:<Backtests/>,paper:<PaperTrading/>,logs:<SystemLogs/>};return <div className="shell"><aside><div className="brand"><div className="mark"><BookOpen size={19}/></div><div><strong>WaveScope</strong><small>BINANCE BOT CONTROL</small></div></div><nav>{nav.map(([id,name,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={17}/>{name}</button>)}</nav><div className="aside-foot"><div className="signed-user"><span>{user.username}</span><small>{user.role}</small></div><button className="auth-button" onClick={logout}><LogOut size={14}/>Log out</button><small>Spot Testnet · Production locked</small></div></aside><main>{pages[page]}</main></div>}
