import {useState} from 'react'
import {Activity,BarChart3,BookOpen,Bot,BrainCircuit,FlaskConical,History,KeyRound,LogIn,ScrollText,Shield,WalletCards,Waves} from 'lucide-react'
import MarketAnalysis from './pages/MarketAnalysis'
import {SystemLogs} from './pages/DataPages'
import ElliottWave from './pages/ElliottWave'
import {Backtests,PaperTrading} from './pages/TradingPages'
import {ActiveTrades,BinanceConnection,BotDashboard,BotStrategies,RiskSettings,TradeHistory} from './pages/ExecutionPages'
import {setAuthToken} from './api'
import './trading.css'
const nav=[['dashboard','Dashboard',Bot],['connection','Binance Connection',KeyRound],['strategies','Bot Strategies',BrainCircuit],['active','Active Trades',Activity],['history','Trade History',History],['risk','Risk Settings',Shield],['analysis','Market Analysis',BarChart3],['elliott','Elliott Wave',Waves],['backtests','Backtesting',FlaskConical],['paper','Paper Trading',WalletCards],['logs','System Logs',ScrollText]]
export default function App(){const [page,setPage]=useState('dashboard'),[token,setToken]=useState(''),[showAuth,setShowAuth]=useState(false),[draft,setDraft]=useState('');const signIn=()=>{setAuthToken(draft);setToken(draft);setDraft('');setShowAuth(false)};const pages={dashboard:<BotDashboard/>,connection:<BinanceConnection/>,strategies:<BotStrategies/>,active:<ActiveTrades/>,history:<TradeHistory/>,risk:<RiskSettings/>,analysis:<MarketAnalysis/>,elliott:<ElliottWave/>,backtests:<Backtests/>,paper:<PaperTrading/>,logs:<SystemLogs/>};return <div className="shell"><aside><div className="brand"><div className="mark"><BookOpen size={19}/></div><div><strong>WaveScope</strong><small>BINANCE BOT CONTROL</small></div></div><nav>{nav.map(([id,name,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={17}/>{name}</button>)}</nav><div className="aside-foot"><button className="auth-button" onClick={()=>setShowAuth(true)}><LogIn size={14}/>{token?'Authenticated':'Sign in'}</button><small>Spot Testnet · Production locked</small></div></aside><main>{pages[page]}</main>{showAuth&&<div className="modal-backdrop"><div className="auth-modal"><p className="eyebrow">APPLICATION AUTHENTICATION</p><h2>Sign in to control the bot</h2><p>Enter your admin, trader, or viewer access token. It remains in memory only and is cleared when this page closes.</p><input type="password" value={draft} onChange={e=>setDraft(e.target.value)} autoFocus placeholder="Access token"/><div className="form-actions"><button onClick={()=>setShowAuth(false)}>Cancel</button><button className="primary" disabled={!draft} onClick={signIn}>Sign in</button></div></div></div>}</div>}
